documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

github:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

frontend:
  - changed-files:
      - any-glob-to-any-file: "apps/web/**"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/gateway/**"
          - "services/**"
