documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

github:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
          - "public/**"
          - "**/*.{html,css,scss}"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "api/**"
          - "server/**"
          - "**/*.{py,go,java}"
