packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
overrides:
  moleculer-cli>moleculer: "^0.15.0"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  es5-ext: false
  esbuild: true
  prisma: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAge: 0
