name: Spell check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check spelling
        uses: codespell-project/actions-codespell@v2
        with:
          path: .github/workflows

